project:
  type: book
  output-dir: ../docs

book:
  title: "Python GIS at UoA"
  author: "Hyesop Shin"
  date: 3/2/26
  
  chapters:
    - index.qmd
    - syllabus.qmd
    - part: 1.0.chapter1-setup.qmd
      chapters:
        - 1.1.installation.qmd
        - 1.2.uv.qmd
        - 1.3.version-control.qmd
        - 1.4.download-from-github.qmd
        
    - part: 2.0.chapter2-geospatial_python.qmd
      chapters:
        - 2.1.basic-python.qmd
        - 2.2.dataframes.qmd
        - 2.3.data-visualisation.qmd
        - 2.4.geospatial.qmd
        - 2.5.creating-functions.qmd
        - 2.6.urban-analytics.qmd
        #- 2.7.geospatial-assignment.qmd
    
    - part: 3.0.chapter3-shiny_python.qmd
      #chapters:
        #- 3.1.webgis-wasm-shiny.qmd
        #- 3.2.shiny-functions-reactivity.qmd
        #- 3.3.routing-and-congestion.qmd
        #- 3.4.origin-destination.qmd
        #- 3.5.networks.qmd
        #- 3.6.shiny-assignment.qmd
    
    - part: 4.0.python-packaging.qmd
      #chapters:
        #- 4.1.package-fundamentals.qmd
        #- 4.2.testing-and-quality.qmd
        #- 4.3.geospatial-package-example.qmd
        #- 4.4.publish-pypi.qmd
        #- 4.8.packaging-assignment.qmd
  
    - part: labs/labs.qmd
      chapters: 
        - labs/lab-week01.qmd
        - labs/lab-week02.qmd
        #- labs/lab-week03.qmd
        #- labs/lab-week04.qmd
        #- labs/lab-week05.qmd
        #- labs/lab-week02.qmd
        #- labs/lab-week03.qmd
        #- labs/lab-week04.qmd
        #- labs/lab-week05.qmd
        #- labs/lab-week06.qmd
        #- labs/lab-week07.qmd
        #- labs/lab-week08.qmd
        #- labs/lab-week09.qmd
        #- labs/lab-week10.qmd

    - references.qmd
bibliography: references.bib
page-navigation: true
  

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
  epub:
    cover-image: cover.png



