project:
  type: book

book:
  title: "Python GIS"
  author: "Hyesop Shin"
  date: 1/14/26
  chapters:
    - index.qmd
    - syllabus.qmd
    - part: 1.chapter1-setup.qmd
      chapters: 
        - 1.1.installation.qmd
        - 1.2.uv.qmd
    - part: 2.chapter2-geospatial_python.qmd
      chapters: 
        - 2.1.basic-python.qmd
        - 2.2.dataframes.qmd
        - 2.3.geospatial.qmd
        - 2.4.urban-analytics.qmd
        - 2.5.midsemtest-assignment.qmd
    - part: 3.chapter3-shiny_python.qmd
      chapters:
        - 3.1.WebGIS. Wasm and Shiny.qmd
        - 3.2.Congestion.qmd
        - 3.3.Origin-Destination.qmd




    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
  epub:
    cover-image: cover.png



